local _, ns = ...

ns.StaticData = ns.StaticData or {}

-- Generated by tools/dungeonmaps/build.py; change tools/dungeonmaps/dungeons.py and run it again.
-- Each dungeon map (docs/dungeon-maps.md), keyed by instanceID (GetInstanceInfo's 8th return):
--   sections[n] = what lifts section n: "enter" (arriving), encounter IDs (ENCOUNTER_START or a
--   kill), "area:<areaID>" (a subzone); with the boss's name.
--   floors[i].art = the 12 tiles (256 px, 4 x 3, row by row) of a map shown at 1002 x 668, or
--   floors[i].minimap = minimap tiles (512 px, tiles = { columns, rows }) shown cropped to crop
--   (texture coordinates of that block). cells = the floor's grid (grid = { columns, rows }) as
--   Codec.EncodeInts of (section, count) runs, row by row; section 0 is never fogged. fog = the
--   color of the parchment around the dungeon.
-- Sources: Forever 1.60.1.70291 (instances, encounters, names, the files), retail 12.1.0.69933
-- (map tables, floor names, encounter journal), AzerothCore a05a043 (spawn and entrance
-- positions).
ns.StaticData.DungeonMapsVersion = "36,43,389,3065"
ns.StaticData.DungeonMaps = {
    [36] = {
        enUS = "Deadmines", deDE = "Todesminen",
        sections = {
            { "enter" },
            { 2741, enUS = "Rhahk'Zor", deDE = "Rhahk'Zor" },
            { 2742, enUS = "Sneed", deDE = "Sneed" },
            { 2743, enUS = "Gilnid", deDE = "Gilnid" },
            { 2744, enUS = "Captain Greenskin", deDE = "Kapitän Grünhaut" },
            { 2745, enUS = "Mr. Smite", deDE = "Handlanger Pein" },
            { 2746, enUS = "Cookie", deDE = "Krümel" },
            { 2747, enUS = "Edwin VanCleef", deDE = "Edwin van Cleef" },
        },
        floors = {
            {
                enUS = "The Deadmines", deDE = "Die Todesminen",
                art = { 449591, 449595, 449596, 449597, 449598, 449599, 449600, 449601, 449602, 449592, 449593, 449594 },
                fog = { 0.557, 0.427, 0.212 },
                grid = { 64, 43 },
                cells = "A8MCIA2DCQAwDCQAwDCQAwDCQAwDCQAsDCUAsDCUAsDCWAqDCWAsDCUAKEGA-CCMEMAEEGA-CCMEMAEEIA8CCKEaA8CCCEiBA-CEgBAgDEoBAIEKAoCE4BAqCE4BAoCEMAEEoBAoCEoBGGEKAoCEmBGKEIAqCEiBGOEGAsCEgBGQEEAuCEeGIAEGIAwCEaGWAyCEaGUA4CEEGKEGACGSA6CGMAIGSA2CGQAIGQA0CGaACGOA2CGcACGOAyCGwBAwCGyBAuCGyBAuCGyBAuCGyBAuCGOAEGgBA0CGGAGGKAIGMAoF",
            },
            {
                enUS = "Ironclad Cove", deDE = "Eiserne Bucht",
                art = { 449603, 449607, 449608, 449609, 449610, 449611, 449612, 449613, 449614, 449604, 449605, 449606 },
                fog = { 0.545, 0.412, 0.192 },
                grid = { 64, 43 },
                cells = "AqVM0BAqCM2BAqCM4BAoCM4BAoCM6BAmCM6BAmCM6BAmCM6BAoCMeKMMOAoCMcACKMMOAoCMcKOOCMMAoCMcKMOEMKAkCMgBACKOOOAgCMkBKEQGKCOQAgCMkBQOOOA6BMqBQOOOA6BMsBQKACOOA0BMwBOGQGOOAuBM2BOKACOQAqBM8BOaAqBMaAIMWOeAqBMaAKMSOgBAqBMYAOMOOiBAqBMMIEAWMMOiBAsBICMIIGAWMKOgBAsBIMMCIGAWMIOgBAuBIWAUMGOiBAsBIYAWOmBAsBIYAWOaACOKAsBIYAYOUAGOKAsBIYAcOMAOOGAsBIYAcOIAkCIYAoDIWAsDIUAwDIOAoL",
            },
        },
    },
    [43] = {
        enUS = "Wailing Caverns", deDE = "Höhlen des Wehklagens",
        sections = {
            { "enter" },
            { 585, enUS = "Lady Anacondra", deDE = "Lady Anacondra" },
            { 586, enUS = "Lord Cobrahn", deDE = "Lord Kobrahn" },
            { 587, enUS = "Kresh", deDE = "Kresh" },
            { 588, enUS = "Lord Pythas", deDE = "Lord Pythas" },
            { 589, enUS = "Skum", deDE = "Skum" },
            { 590, enUS = "Lord Serpentis", deDE = "Lord Serpentis" },
            { 591, enUS = "Verdan the Everliving", deDE = "Verdan der Ewiglebende" },
            { 592, enUS = "Mutanus the Devourer", deDE = "Mutanus der Verschlinger" },
        },
        floors = {
            {
                art = { 448454, 448458, 448459, 448460, 448461, 448462, 448463, 448464, 448465, 448455, 448456, 448457 },
                fog = { 0.545, 0.412, 0.192 },
                grid = { 64, 43 },
                cells = "AqFSOAyDSSAiDSeAiDSeAiDSeAiDSeAyCKKAGSeAmCKGAEKQACSeAmCKaACSWIGAoCKaACSIIUAoCKaACSCEEIYAmCKaACEGIYAmCKaEMIUAOQGAyBKaEOISQUAyBKaEOIQQaAuBGIKSEOISQYAuBGKKSEOIQQYAwBGKKMEUIOQYAwBGKKMESIQQQOKAuBGKKMEWIIQUOKAuBGQKGEWCQQKOOAuBGUAEEGACEKCQQKOQAsBGUAMEKCQQGOWAqBGUAaCMQGOaAoBGSAeCGQGOcAoBGSAeCGQEMKOWAuBGIAgBCEMWOSA4CMUOUA6CMWOQA6CMUOSA6CMaOMA6CMcOKA8CMeOIA6CMgBOGA6CMiBOEA6CMiBA-CMiBAkDMaAmDMSAoN",
            },
        },
    },
    [389] = {
        enUS = "Ragefire Chasm", deDE = "Ragefireabgrund",
        sections = {
            { "enter" },
            { 2732, enUS = "Oggleflint", deDE = "Flintauge" },
            { 2733, enUS = "Taragaman the Hungerer", deDE = "Taragaman der Hungerleider" },
            { 2734, enUS = "Jergosh the Invoker", deDE = "Jergosh der Herbeirufer" },
            { 2735, enUS = "Bazzalan", deDE = "Bazzalan" },
        },
        floors = {
            {
                art = { 449736, 449740, 449741, 449742, 449743, 449744, 449745, 449746, 449747, 449737, 449738, 449739 },
                fog = { 0.537, 0.412, 0.192 },
                grid = { 64, 43 },
                cells = "AqGCMA0DCOAyDCUAsDCUAuDCSAqDCWAqDCWAqDCSAuDCUAkDEKCSAkDEOCOAiDEQCOAiDESCMAgDESCOA8CEYCMAsCGQEYCMAqCGSEYCOAoCGSEWCQAmCGUEYCOAmCGWEUCQAkCGYEWCOAkCGaEWCMAiCGcEEGCEQCMAiCGkBEMACCMAiCGoBEICIAmCGmBEMCIAmCGkBEOCIAmCGiBEUCEAqCGeEWCCAmCGkBEWAmCGKICGCAGGOACEWAmCGIIIAGGKAGEIACEKAmCKGIMAEGIAGEKAwCKIIOKEGCKIACEIAyCKIIOKQEGA0CKMIIKSA6CKqBA2CKqBA4CKoBAgDKcAsDKGAEKGAiG",
            },
        },
    },
    [3065] = {
        enUS = "The Hall of Thanes", deDE = "Die Halle der Thanen",
        sections = {
            { "enter" },
            { 3493, enUS = "Faldrim Anvilmar", deDE = "Faldrim Anvilmar" },
            { 3494, enUS = "Plunder", deDE = "Plünderung" },
            { 3495, enUS = "Infurnus", deDE = "Infurnus" },
            { 3496, enUS = "Durgen Dirgehammer", deDE = "Durgen Dirgehammer" },
        },
        floors = {
            {
                minimap = { 7726086, 7726092, 7726140, 7726146, 7726194, 7726200 },
                tiles = { 2, 3 },
                crop = { 0.225, 0.25, 0.8, 0.7667 },
                fog = { 0.439, 0.443, 0.439 },
                grid = { 64, 86 },
                cells = "A6SKGA4DKMA0DKOAwDKSAsDKUAsDKWAoDKaAmDKcAiDKeAiDKgBA-CKkBA6CKmBA6CKoBA2CKsBA0CKsBAgBGKAoBKwBAQGYAoBKwBAQGaAmBKwBAQGeAkBKsBASGeAmBKqBASGeAoBKmBAUGeAoBKkBAWGgBAmBKeGEAYGgBAQKKAKKeGGAYGgBAMKSAGKcGIAYGgBAMKSAGKaGGIEAYGeAMKWAGKWGGIGAYGeAMKwBGGIIAYGeAMKuBGGIKAYGeAMKsBGGIMAYGiBAIKqBGGIQAWGkBKuBGGISAWGkBKsBGGIUAWGmBKoBGGIWAWGoBKkBGGIYAUGsBKgBGGIaAUGuBKcGGIcAUGwBKMGSIeAWGqCIgBAWGoCIiBAWGoCIiBAWGoCIiBAYGmCIiBAYGmCIiBAYGmCIiBAaGkCIiBAcGiCIiBAeGgCIiBAgBG-BIiBAiBGOAEGqBIiBAkBGKAIGoBIgBA4BGoBIgBA4BGoBIeAiCGgBIGAEISAmBEWACEIGgBIWAqBEgBGgBIWAqBEgBGgBIWAqBEiBGeIYAoBEkBGaIaAoBEgBCaGEIaAoBEgBCcGCIaAoBEgBCeIaAoBEgBCgBIYAoBEgBCgBIWAqBEiBCeIWAqBEWACCmBACIWAiCCmBA6CCmBA8CCkBAkDCSAuDCSAuDCSAuDCSAuDCSAuDCSAuDCSAuDCSAuDCSA6R",
            },
        },
    },
}
