local T = require("testlib")
local Stubs = require("wow_stubs")
local describe, it = T.describe, T.it

local function start(opts)
    local ns = Stubs.LoadAddon(opts)
    Stubs.Login()
    return ns
end

local function deaths(ns)
    return ns.Store:GetRecordsOfType("DEATH")
end

describe("deaths", function()
    it("records where the character died, in the zone's name", function()
        local ns = start()
        Stubs.SetBestMap(1412)
        Stubs.SetPosition(1, -2894.3, -238.8)
        Stubs.Fire("PLAYER_DEAD")
        local list = deaths(ns)
        T.eq(#list, 1)
        T.same(list[1].data, { map = 1412, c = 1, x = -2894, y = -239 })
        T.eq(ns.RecordTypes:Render(list[1]), "Died in Mulgore")
        T.eq(ns.RecordTypes:CategoryOf("DEATH"), "adventure")
        T.eq(#ns.Log:GetEntries(), 0)
    end)

    it("names the subzone with the zone", function()
        local ns = start()
        Stubs.SetBestMap(1412)
        Stubs.SetSubZone("Red Cloud Mesa")
        Stubs.SetPosition(1, 0, 0)
        Stubs.Fire("PLAYER_DEAD")
        local record = deaths(ns)[1]
        T.eq(record.data.sub, "Red Cloud Mesa")
        T.eq(ns.RecordTypes:Render(record), "Died in Red Cloud Mesa, Mulgore")
        record.data.sub = "Mulgore" -- the zone's own name as its subzone
        T.eq(ns.RecordTypes:Render(record), "Died in Mulgore")
    end)

    it("counts one death once, even if the event comes twice", function()
        local ns = start()
        Stubs.SetPosition(1, 0, 0)
        Stubs.Fire("PLAYER_DEAD")
        Stubs.Fire("PLAYER_DEAD")
        Stubs.Advance(5)
        Stubs.Fire("PLAYER_DEAD")
        T.eq(#deaths(ns), 1)
        Stubs.Advance(60)
        Stubs.Fire("PLAYER_DEAD")
        T.eq(#deaths(ns), 2)
    end)

    it("inside an instance keeps only the map, since there is no position", function()
        local ns = start()
        Stubs.SetInstance(389, "party", "Ragefire Chasm")
        Stubs.SetPosition()
        Stubs.Fire("PLAYER_DEAD")
        local list = deaths(ns)
        T.same(list[1].data, { map = 1411 })
        T.eq(ns.RecordTypes:Render(list[1]), "Died", "a map without a name: just the death")
    end)

    it("reads well in German", function()
        local ns = start({ locale = "deDE" })
        Stubs.SetBestMap(1412)
        Stubs.SetPosition(1, 0, 0)
        Stubs.Fire("PLAYER_DEAD")
        T.eq(ns.RecordTypes:Render(deaths(ns)[1]), "In Mulgore gestorben")
        Stubs.Advance(60)
        Stubs.SetSubZone("Red Cloud Mesa")
        Stubs.Fire("PLAYER_DEAD")
        T.eq(ns.RecordTypes:Render(deaths(ns)[2]), "In Red Cloud Mesa, Mulgore gestorben")
    end)

    it("records nothing when turned off", function()
        local ns = start()
        ns.Trackers:SetWanted("Deaths", false)
        Stubs.Fire("PLAYER_DEAD")
        T.eq(#deaths(ns), 0)
    end)
end)
