local T = require("testlib")
local Stubs = require("wow_stubs")
local describe, it = T.describe, T.it

local function records(ns)
    return ns.Store:GetDayRecords(20261003)
end

describe("level ups", function()
    it("records a level up with the zone", function()
        local ns = Stubs.LoadAddon({ level = 11 })
        Stubs.Login()
        Stubs.SetLevel(12)
        Stubs.Fire("PLAYER_LEVEL_UP", 12)
        local list = records(ns)
        T.eq(#list, 1)
        T.same(list[1].data, { level = 12, map = 1411 })
        T.eq(ns.RecordTypes:Render(list[1]), "Reached level 12")
    end)

    it("ignores a duplicate event for the same level", function()
        local ns = Stubs.LoadAddon({ level = 11 })
        Stubs.Login()
        Stubs.Fire("PLAYER_LEVEL_UP", 12)
        Stubs.Fire("PLAYER_LEVEL_UP", 12)
        T.eq(#records(ns), 1)
    end)

    it("doesn't back-fill levels gained while the addon was off", function()
        local ns = Stubs.LoadAddon({ level = 20 })
        Stubs.Login()
        T.eq(#records(ns), 0)
        T.eq(ns.Store:GetState("level"), 20)
    end)

    it("falls back to UnitLevel when the event argument is secret", function()
        local ns = Stubs.LoadAddon({ level = 11 })
        Stubs.Login()
        Stubs.Fire("PLAYER_LEVEL_UP", Stubs.SECRET)
        T.eq(#records(ns), 0, "nothing before the timer")
        Stubs.SetLevel(12)
        Stubs.Advance(1)
        T.eq(#records(ns), 1)
        T.eq(records(ns)[1].data.level, 12)
    end)

    it("survives logout and login without duplicates", function()
        Stubs.LoadAddon({ level = 11 })
        Stubs.Login()
        Stubs.Fire("PLAYER_LEVEL_UP", 12)
        Stubs.Relog({ level = 12 })
        local ns = Stubs.Relog({ level = 12 }, true)
        Stubs.Fire("PLAYER_LEVEL_UP", 12) -- replayed event after the reload
        T.eq(#records(ns), 1)
        Stubs.Fire("PLAYER_LEVEL_UP", 13)
        local list = records(ns)
        T.eq(#list, 2)
        T.eq(list[2].id, 2, "ids continue across logins")
    end)
end)
