local T = require("testlib")
local Stubs = require("wow_stubs")
local serialize = require("serialize")
local describe, it = T.describe, T.it

describe("saved data", function()
    it("is plain data the client can write and read back", function()
        local ns = Stubs.LoadAddon({ level = 11 })
        Stubs.Login()
        Stubs.Fire("PLAYER_LEVEL_UP", 12)
        ns.Store:Count("gather", 2770, 3)
        ns.Players:Intern("Player-1-0000CCCC", "Friend", "Forever", "PRIEST")
        ns.Probe:Run()
        Stubs.Fire("PLAYER_LOGOUT")
        -- Errors on functions, metatables, secrets or shared table references.
        local account = serialize.RoundTrip(WayscribeDB)
        local journal = serialize.RoundTrip(WayscribeCharDB)
        T.same(account, WayscribeDB)
        T.same(journal, WayscribeCharDB)
    end)

    it("reloads into the same journal with indexes intact", function()
        local ns = Stubs.LoadAddon({ level = 11 })
        Stubs.Login()
        Stubs.Fire("PLAYER_LEVEL_UP", 12)
        ns.Players:Intern("Player-1-0000CCCC", "Friend", "Forever", "PRIEST")
        ns = Stubs.Relog()
        T.same(ns.Store:GetDayKeys(), { 20261003 })
        T.eq(ns.Store:GetDayRecords(20261003)[1].data.level, 12)
        T.eq(ns.Players:Intern("Player-1-0000CCCC"), 1, "players keep their id")
    end)
end)

describe("journal window", function()
    it("shows each day's entries and counter summaries", function()
        local ns = Stubs.LoadAddon({ level = 11 })
        Stubs.Login()
        Stubs.Fire("PLAYER_LEVEL_UP", 12)
        Stubs.state.itemNames[2770] = "Copper Ore"
        ns.Store:Count("gather", 2770, 3)
        ns.Slash:Handle("")
        T.truthy(_G.WayscribeJournalFrame:IsShown())
        T.eq(ns.DayView.ui.title:GetText(), "Saturday, October 3, 2026")
        T.same(Stubs.Texts(ns.DayView.ui.content), {
            "12:00 PM", "Reached level 12",
            "Gathered 3× Copper Ore",
            "Sessions: 12:00 PM - now",
        })
        T.eq(#ns.Log:GetEntries(), 0)
    end)
end)

describe("slash commands", function()
    it("simulate only works in developer mode and can be cleared", function()
        local ns = Stubs.LoadAddon()
        Stubs.Login()
        ns.Slash:Handle("simulate LEVEL_UP level=30")
        T.eq(ns.Store:GetStats().records, 0)

        ns.Slash:Handle("dev")
        ns.Slash:Handle("simulate level_up level=30 map=1411")
        local list = ns.Store:GetDayRecords(20261003)
        T.eq(#list, 1)
        T.truthy(list[1].sim)
        T.same(list[1].data, { level = 30, map = 1411 })

        ns.Slash:Handle("simulate LEVEL_UP lvl=30")
        T.eq(ns.Store:GetStats().records, 1, "invalid data is rejected")

        ns.Slash:Handle("simulate clear")
        T.eq(ns.Store:GetStats().records, 0)
    end)

    it("an unknown command shows help instead of failing", function()
        local ns = Stubs.LoadAddon()
        Stubs.Login()
        ns.Slash:Handle("doesnotexist")
        local printed = Stubs.Printed()
        T.truthy(printed[#printed]:find("Commands"))
    end)

    it("rebuild and stats run on a real journal", function()
        local ns = Stubs.LoadAddon({ level = 11 })
        Stubs.Login()
        Stubs.Fire("PLAYER_LEVEL_UP", 12)
        ns.Slash:Handle("rebuild")
        ns.Slash:Handle("stats")
        local printed = Stubs.Printed()
        T.truthy(printed[#printed - 2]:find("rebuilt from 1"))
        T.truthy(printed[#printed - 1]:find("1 entries on 1 days"))
        T.truthy(printed[#printed]:find("Footsteps: 0 trails on 0 days"))
    end)
end)
