local T = require("testlib")
local Stubs = require("wow_stubs")
local describe, it = T.describe, T.it

describe("sessions", function()
    it("a login starts a session and logout closes it", function()
        local ns = Stubs.LoadAddon()
        local start = Stubs.Now()
        Stubs.Login()
        local session = ns.Store:GetCurrentSession()
        T.eq(session.s, start)
        T.eq(session.e, nil)
        Stubs.Advance(600)
        Stubs.Fire("PLAYER_LOGOUT")
        T.eq(session.e, start + 600)
    end)

    it("a /reload continues the same session", function()
        Stubs.LoadAddon()
        local start = Stubs.Now()
        Stubs.Login()
        Stubs.Advance(600)
        local ns = Stubs.Relog(nil, true)
        local month = ns.charDB.months[202610]
        T.eq(#month.sessions, 1)
        T.eq(month.sessions[1].s, start)
        T.eq(month.sessions[1].e, nil, "re-opened")
    end)

    it("a new login starts a new session", function()
        Stubs.LoadAddon()
        Stubs.Login()
        Stubs.Advance(600)
        local ns = Stubs.Relog()
        T.eq(#ns.charDB.months[202610].sessions, 2)
        T.eq(ns.charDB.months[202610].sessions[1].e, Stubs.Now())
    end)

    it("loading screens don't touch the session", function()
        local ns = Stubs.LoadAddon()
        Stubs.Login()
        Stubs.Fire("PLAYER_ENTERING_WORLD", false, false)
        T.eq(#ns.charDB.months[202610].sessions, 1)
    end)

    it("counts play time per month", function()
        Stubs.LoadAddon()
        Stubs.Login()
        Stubs.Advance(1200)
        local ns = Stubs.Relog(nil, true)
        Stubs.Advance(300)
        Stubs.Fire("PLAYER_LOGOUT")
        T.eq(ns.Store:GetMonthSummary(202610).playSeconds, 1500)
    end)
end)
